modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-morecatvariants/issues"
license = "ARR"

[[mods]]
modId = "morecatvariants"
version = "${version}"
displayName = "More Cat Variants"
authors = "mahmudindev"
description = '''
Add more cat variants.
'''
logoFile = "assets/morecatvariants/icon.png"

[[dependencies.morecatvariants]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morecatvariants]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
