modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-morecatvariants/issues"
license = "ARR"

[[mods]]
modId = "morecatvariants"
version = "${version}"
displayName = "More Cat Variants"
authors = "mahmudindev"
description = '''
Add more cat variants.
'''
logoFile = "assets/morecatvariants/icon.png"

[[dependencies.morecatvariants]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morecatvariants]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "morecatvariants.mixins.json"
